# docker-compose.yml for MySQL
version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassword1234
    ports:
      - "3306:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - shared-network
    
networks:
    shared-network:
      external: true

volumes:
    todo-mysql-data:
      external: true
  